# Use postgres/example user/password credentials
version: "3.1"

services:
  keyboard_learn_words:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend-bridge
    ports:
      - "3006:3006"

networks:
  backend-bridge:
    driver: bridge
